<a href="https://colab.research.google.com/github/sathana495/ML-project/blob/main/Movie_Recommendation_System1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**step 1 : import dataset**

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv(r"/content/drive/MyDrive/dataset/tamil_movies_dataset.csv")

In [ ]:
df

,movie_id,title,year,genre,director,lead_actor,lead_actress,rating,votes,language,duration_min,streaming_platform,box_office_crore,mood,audience_type,sequel_available
0,1,Vikram,2022,Action/Thriller,Lokesh Kanagaraj,Kamal Haasan,Narain,8.4,120000,Tamil,174,Amazon Prime,300.0,Intense,Adults,Yes
1,2,Ponniyin Selvan 1,2022,Historical/Drama,Mani Ratnam,Vikram,Aishwarya Rai,7.8,95000,Tamil,167,Amazon Prime,250.0,Epic,Family,Yes
2,3,Ponniyin Selvan 2,2023,Historical/Drama,Mani Ratnam,Vikram,Aishwarya Rai,7.5,80000,Tamil,162,Amazon Prime,180.0,Epic,Family,No
3,4,Jailer,2023,Action/Drama,Nelson Dilipkumar,Rajinikanth,Tamannaah,7.2,110000,Tamil,168,Netflix,600.0,Masala,Family,No
4,5,Leo,2023,Action/Thriller,Lokesh Kanagaraj,Vijay,Trisha,7.4,130000,Tamil,164,Netflix,650.0,Intense,Adults,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Madras,2014,Drama/Action,Pa. Ranjith,Karthi,Catherine Tresa,8.1,60000,Tamil,144,YouTube,NaN,Powerful,Adults,No
96,97,Kadal,2013,Romance/Drama,Mani Ratnam,Arjun Allu,Thulasi Nair,6.0,40000,Tamil,155,Hotstar,NaN,Romantic,Youth,No
97,98,Santhosh Subramaniam,2008,Romance/Comedy,Thiru,Jayam Ravi,Genelia,7.8,50000,Tamil,148,YouTube,NaN,Fun Romance,Youth,No
98,99,Vaaranam Aayiram,2008,Drama/Romance,Gautham Vasudev Menon,Suriya,Sameera Reddy,7.9,65000,Tamil,180,Hotstar,NaN,Emotional,Family,No
99,100,Poo,2008,Romance/Drama,Sasi,Srikanth,Poonam Bajwa,7.8,35000,Tamil,128,YouTube,NaN,Romantic,Youth,No

In [ ]:
df.describe()

,movie_id,year,rating,votes,duration_min,box_office_crore
count,100.000000,100.000000,100.000000,100.000000,100.000000,29.000000
mean,50.500000,2013.870000,7.577000,68120.000000,144.340000,240.862069
std,29.011492,7.336989,0.769869,55346.526357,21.277968,357.196597
min,1.000000,1986.000000,5.500000,10000.000000,97.000000,20.000000
25%,25.750000,2010.000000,7.000000,40000.000000,130.000000,60.000000
50%,50.500000,2016.000000,7.750000,60000.000000,147.500000,100.000000
75%,75.250000,2019.000000,8.200000,80000.000000,161.250000,250.000000
max,100.000000,2023.000000,8.800000,500000.000000,185.000000,1800.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   movie_id            100 non-null    int64
 1   title               100 non-null    object
 2   year                100 non-null    int64
 3   genre               100 non-null    object
 4   director            100 non-null    object
 5   lead_actor          100 non-null    object
 6   lead_actress        100 non-null    object
 7   rating              100 non-null    float64
 8   votes               100 non-null    int64
 9   language            100 non-null    object
 10  duration_min        100 non-null    int64
 11  streaming_platform  100 non-null    object
 12  box_office_crore    29 non-null     float64
 13  mood                100 non-null    object
 14  audience_type       100 non-null    object
 15  sequel_available    100 non-null    object
dtypes: float64(2), int64(4), object(10)
memory usage: 12.6+ KB

In [ ]:
df.isna().sum()

movie_id               0
title                  0
year                   0
genre                  0
director               0
lead_actor             0
lead_actress           0
rating                 0
votes                  0
language               0
duration_min           0
streaming_platform     0
box_office_crore      71
mood                   0
audience_type          0
sequel_available       0
dtype: int64

**Step 2 :Fix Null Values**

In [ ]:
median_box_office = df['box_office_crore'].median()
df['box_office_crore'] = df['box_office_crore'].fillna(median_box_office)
print(df.isna().sum())

movie_id              0
title                 0
year                  0
genre                 0
director              0
lead_actor            0
lead_actress          0
rating                0
votes                 0
language              0
duration_min          0
streaming_platform    0
box_office_crore      0
mood                  0
audience_type         0
sequel_available      0
dtype: int64

In [ ]:
df.isna().sum()

movie_id              0
title                 0
year                  0
genre                 0
director              0
lead_actor            0
lead_actress          0
rating                0
votes                 0
language              0
duration_min          0
streaming_platform    0
box_office_crore      0
mood                  0
audience_type         0
sequel_available      0
dtype: int64

**step 3 : drop unwanted colunms**

In [ ]:
df=df.drop(['director','lead_actor','lead_actress','streaming_platform','language'],axis=1)

**step 4 :preprocessing the input data**

In [ ]:
df['sequel_available'] = df['sequel_available'].replace({'Yes': 1, 'No': 0}).astype(int)

/tmp/ipykernel_18931/747090274.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sequel_available'] = df['sequel_available'].replace({'Yes': 1, 'No': 0}).astype(int)

In [ ]:
df.head()

,movie_id,title,year,genre,rating,votes,duration_min,box_office_crore,mood,audience_type,sequel_available
0,1,Vikram,2022,Action/Thriller,8.4,120000,174,300.0,Intense,Adults,1
1,2,Ponniyin Selvan 1,2022,Historical/Drama,7.8,95000,167,250.0,Epic,Family,1
2,3,Ponniyin Selvan 2,2023,Historical/Drama,7.5,80000,162,180.0,Epic,Family,0
3,4,Jailer,2023,Action/Drama,7.2,110000,168,600.0,Masala,Family,0
4,5,Leo,2023,Action/Thriller,7.4,130000,164,650.0,Intense,Adults,0

In [ ]:
print(df['genre'].unique())

['Action/Thriller' 'Historical/Drama' 'Action/Drama' 'Family/Drama'
 'Legal Drama' 'Biographical Drama' 'Action/Comedy' 'Drama/Social'
 'Action/Crime' 'Romance/Drama' 'Social Drama' 'Anthology/Drama'
 'Sports/Action' 'Action/Historical' 'Sci-Fi/Action' 'Thriller/Drama'
 'Romance' 'Crime/Drama' 'Drama/Romance' 'Thriller/Horror' 'Comedy/Drama'
 'Crime/Thriller' 'Drama' 'Sci-Fi/Thriller' 'Sports/Drama'
 'Political/Drama' 'Family/Comedy' 'Political/Thriller'
 'Romantic/Thriller' 'Comedy/Romance' 'Romance/Musical' 'Romance/Comedy'
 'Romance/Action' 'Romance/Thriller' 'Romance/Social Drama'
 'Horror/Comedy' 'Horror/Romance' 'Horror/Thriller' 'Horror'
 'Horror/Action' 'Drama/Action' 'Comedy/Thriller' 'Drama/Comedy'
 'Horror/Drama' 'Fantasy/Action']

In [ ]:
df['genre']=df['genre'].replace({'Action/Thriller':1,'Historical/Drama':2,'Action/Drama':3,'Family/Drama':4,'Legal Drama':5,'Biographical Drama':6,'Action/Comedy':7,'Drama/Social':8,'Action/Crime':9,'Romance/Drama':10,'Social Drama':11,'Anthology/Drama':12,'Sports/Action':13,'Action/Historical':14,'Sci-Fi/Action':15,'Thriller/Drama':16,'Romance':17,'Crime/Drama':19,'Drama/Romance':47,'Thriller/Horror':20,'Comedy/Drama':21,'Crime/Thriller':22,'Drama':23,'Sci-Fi/Thriller':24,'Sports/Drama':25,'Political/Drama':26,'Family/Comedy':27,'Political/Thriller':28,'Romantic/Thriller':29,'Comedy/Romance':31,'Romance/Musical':32,'Romance/Comedy':33,'Romance/Action':34,'Romance/Thriller':35,'Romance/Social Drama':36,'Horror/Comedy':37,'Horror/Romance':38,'Horror/Thriller':39,'Horror':40,'Horror/Action':41,'Drama/Action':42,'Comedy/Thriller':43,'Drama/Comedy':44,'Horror/Drama':45,'Fantasy/Action':46})

/tmp/ipykernel_18931/2485370982.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['genre']=df['genre'].replace({'Action/Thriller':1,'Historical/Drama':2,'Action/Drama':3,'Family/Drama':4,'Legal Drama':5,'Biographical Drama':6,'Action/Comedy':7,'Drama/Social':8,'Action/Crime':9,'Romance/Drama':10,'Social Drama':11,'Anthology/Drama':12,'Sports/Action':13,'Action/Historical':14,'Sci-Fi/Action':15,'Thriller/Drama':16,'Romance':17,'Crime/Drama':19,'Drama/Romance':47,'Thriller/Horror':20,'Comedy/Drama':21,'Crime/Thriller':22,'Drama':23,'Sci-Fi/Thriller':24,'Sports/Drama':25,'Political/Drama':26,'Family/Comedy':27,'Political/Thriller':28,'Romantic/Thriller':29,'Comedy/Romance':31,'Romance/Musical':32,'Romance/Comedy':33,'Romance/Action':34,'Romance/Thriller':35,'Romance/Social Drama':36,'Horror/Comedy':37,'Horror/Romance':38,'Horror/Thriller':39,'Horror':40,'Horror/Action':41,'Drama/Action':42,'Comedy/Thriller':43,'Drama/Comedy':44,'Horror/Drama':45,'Fantasy/Action':46})

In [ ]:
df.head()

,movie_id,title,year,genre,rating,votes,duration_min,box_office_crore,mood,audience_type,sequel_available
0,1,Vikram,2022,1,8.4,120000,174,300.0,Intense,Adults,1
1,2,Ponniyin Selvan 1,2022,2,7.8,95000,167,250.0,Epic,Family,1
2,3,Ponniyin Selvan 2,2023,2,7.5,80000,162,180.0,Epic,Family,0
3,4,Jailer,2023,3,7.2,110000,168,600.0,Masala,Family,0
4,5,Leo,2023,1,7.4,130000,164,650.0,Intense,Adults,0

In [ ]:
print(df['mood'].unique())

['Intense' 'Epic' 'Masala' 'Emotional' 'Motivational' 'Powerful'
 'Inspiring' 'Fun' 'Cool' 'Nostalgic' 'Mind-bending' 'Sci-Fi'
 'Psychological' 'Romantic' 'Gritty' 'Thrilling' 'Quirky' 'Gripping'
 'Wholesome' 'Complex' 'Intense Romance' 'Fun Romance' 'Patriotic Romance'
 'Modern Romance' 'Fantasy Horror' 'Comedy Horror' 'Supernatural' 'Scary'
 'Psychological Horror' 'Fun Horror' 'Zombie Thriller' 'Intense Horror'
 'Dark Romance' 'Romantic Thriller' 'Fantasy' 'Raw Romance']

In [ ]:
df['mood']=df['mood'].replace({'Intense':1,'Epic':2,'Masala':3,'Emotional':4,'Powerful':5,'Inspiring':6,'Fun':7,'Cool':8,'Nostalgic':9,'Mind-bending':10,'Sci-Fi':11,'Psychological':12,'Romantic':13,'Gritty':14,'Thrilling':15,'Quirky':16,'Gripping':17,'Wholesome':18,'Complex':19,'Intense Romance':20,'Fun Romance':21,'Patriotic Romance':22,'Modern Romance':23,'Fantasy Horror':24,'Comedy Horror':25,'Supernatural':26,'Scary':27,'Psychological Horror':28,'Fun Horror':29,'Zombie Thriller':30,'Intense Horror':31,'Dark Romance':32,'Romantic Thriller':33,'Fantasy':34,'Raw Romance':35,'Motivational':36})

/tmp/ipykernel_18931/851027271.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['mood']=df['mood'].replace({'Intense':1,'Epic':2,'Masala':3,'Emotional':4,'Powerful':5,'Inspiring':6,'Fun':7,'Cool':8,'Nostalgic':9,'Mind-bending':10,'Sci-Fi':11,'Psychological':12,'Romantic':13,'Gritty':14,'Thrilling':15,'Quirky':16,'Gripping':17,'Wholesome':18,'Complex':19,'Intense Romance':20,'Fun Romance':21,'Patriotic Romance':22,'Modern Romance':23,'Fantasy Horror':24,'Comedy Horror':25,'Supernatural':26,'Scary':27,'Psychological Horror':28,'Fun Horror':29,'Zombie Thriller':30,'Intense Horror':31,'Dark Romance':32,'Romantic Thriller':33,'Fantasy':34,'Raw Romance':35,'Motivational':36})

In [ ]:
df.head()

,movie_id,title,year,genre,rating,votes,duration_min,box_office_crore,mood,audience_type,sequel_available
0,1,Vikram,2022,1,8.4,120000,174,300.0,1,Adults,1
1,2,Ponniyin Selvan 1,2022,2,7.8,95000,167,250.0,2,Family,1
2,3,Ponniyin Selvan 2,2023,2,7.5,80000,162,180.0,2,Family,0
3,4,Jailer,2023,3,7.2,110000,168,600.0,3,Family,0
4,5,Leo,2023,1,7.4,130000,164,650.0,1,Adults,0

In [ ]:
print(df['audience_type'].unique())

['Adults' 'Family' 'Youth']

In [ ]:
df['audience_type']=df['audience_type'].replace({'Adults':1,'Family':2,'Youth':3})

/tmp/ipykernel_18931/2995733454.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['audience_type']=df['audience_type'].replace({'Adults':1,'Family':2,'Youth':3})

In [ ]:
df.head()

,movie_id,title,year,genre,rating,votes,duration_min,box_office_crore,mood,audience_type,sequel_available
0,1,Vikram,2022,1,8.4,120000,174,300.0,1,1,1
1,2,Ponniyin Selvan 1,2022,2,7.8,95000,167,250.0,2,2,1
2,3,Ponniyin Selvan 2,2023,2,7.5,80000,162,180.0,2,2,0
3,4,Jailer,2023,3,7.2,110000,168,600.0,3,2,0
4,5,Leo,2023,1,7.4,130000,164,650.0,1,1,0

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
Scaler = StandardScaler()

In [ ]:
list2 = ['votes','duration_min','box_office_crore']

In [ ]:
df[list2] = Scaler.fit_transform(df[list2])

In [ ]:
df.head()

,movie_id,title,year,genre,rating,votes,duration_min,box_office_crore,mood,audience_type,sequel_available
0,1,Vikram,2022,1,8.4,0.942089,1.400952,0.797641,1,1,1
1,2,Ponniyin Selvan 1,2022,2,7.8,0.488114,1.070316,0.547047,2,2,1
2,3,Ponniyin Selvan 2,2023,2,7.5,0.215729,0.834148,0.196215,2,2,0
3,4,Jailer,2023,3,7.2,0.760499,1.117550,2.301207,3,2,0
4,5,Leo,2023,1,7.4,1.123679,0.928615,2.551801,1,1,0

**step 5 : split the test and train data**

In [ ]:
x=df.drop(['title'],axis=1)

In [ ]:
y=df['title']

In [ ]:
from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.2,random_state=42)

**step 6 : use NearestNeighbors model**

In [ ]:
from sklearn.neighbors import NearestNeighbors

from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
model=NearestNeighbors(n_neighbors=6, metric='euclidean')
model.fit(x_train,y_train)

NearestNeighbors(metric='euclidean', n_neighbors=6)

In [ ]:
def rec(movie_title):
    if movie_title not in df['title'].values:
        return "Movie not found in the dataset. Please enter a valid movie title."

    movie_idx = df[df['title'] == movie_title].index[0]


    query_point = x.loc[[movie_idx]]


    distances, indices = model.kneighbors(query_point)


    recommended_movie_titles = df.iloc[indices[0][1:]]["title"]
    return recommended_movie_titles

# Test it
movie = input("enter the movie name: ")
print(rec(movie))

enter the movie name: Leo
9     Soorarai Pottru
8            Jai Bhim
18             Asuran
10             Master
6             Thunivu
Name: title, dtype: object